version: 2

models:
  - name: stg_events
    columns:
      - name: event_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null
      - name: event_type
        tests:
          - accepted_values:
              values: ['purchase', 'refund']
