name: 'day26_orders'
version: '1.0.0'
config-version: 2

profile: 'day26_orders'

model-paths: ["models"]
seed-paths: ["seeds"]

models:
  day26_orders:
    staging:
      +materialized: view
    marts:
      +materialized: table
